name: galeria_onboarding
description: "A new Flutter project."
publish_to: 'none' # Remove a linha com "kages."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/cadeira_estofada_before.png
    - assets/images/cadeira_estofada_after.png
    - assets/images/relogio_before.png
    - assets/images/relogio_after.png
    - assets/images/isqueiro_zippo_before.png
    - assets/images/isqueiro_zippo_after.png
